"""
Crypto Centralized Risk, Target, & Sizing Authority — §4, §5, §10, §18
Enforces:
  1. No structural stop clamping (Reject invalid structure instead of forcing arbitrary tight stop).
  2. Realistic target generation based on market structure and envelope ceilings.
  3. Strict fractional position sizing for BTC/ETH spot & perpetuals.
  4. Independent Two-Clock lifecycles (Trigger TTL vs Active Holding Time Stop).
"""
from __future__ import annotations

import math
from decimal import Decimal
from typing import Literal, Optional
from pydantic import BaseModel, Field
import structlog

logger = structlog.get_logger()

CryptoDirection = Literal["LONG", "SHORT"]
CryptoTimeframe = Literal["1m", "3m", "5m", "15m", "1h", "1d"]


class CryptoStrategySetup(BaseModel):
    """Raw proposal generated by an individual crypto strategy algorithm."""
    strategy_name: str
    symbol: str = "BTCUSDT"
    direction: CryptoDirection
    timeframe: CryptoTimeframe = "1m"
    is_scalp: bool = True
    spot_price: Decimal
    entry_trigger: Decimal
    raw_structural_stop: Decimal
    structural_target_candidates: list[Decimal] = Field(default_factory=list)
    atr_val: Decimal = Decimal("100.0")
    confidence: float = 75.0


class CryptoValidatedRiskDecision(BaseModel):
    accepted: bool
    rejection_reason: Optional[str] = None
    config_version: int = 1

    # Final validated prices
    entry_price: Decimal
    stop_loss: Decimal
    target_1: Decimal
    target_2: Decimal

    # Risk / Reward metrics
    risk_points: float
    reward_t1_points: float
    reward_t2_points: float
    risk_reward_t1: float
    risk_reward_t2: float

    # Independent Lifecycles
    trigger_ttl_seconds: int
    active_time_stop_seconds: int
    runner_ttl_seconds: int = 300

    # Position Sizing
    quantity: float
    notional_usd: float
    max_usd_loss: float
    precision_decimals: int = 3


# Baseline asset envelopes for crypto pairs
CRYPTO_RISK_ENVELOPES = {
    "BTCUSDT": {
        "1m_scalp": {
            "min_risk_pts": 100.0,
            "max_risk_pts": 600.0,
            "t1_ceiling_pts": 800.0,
            "t2_ceiling_pts": 1400.0,
            "atr_multiplier": 1.1,
            "min_rr": 1.25,
            "trigger_ttl_seconds": 180,
            "active_time_stop_seconds": 900,
            "runner_ttl_seconds": 300,
            "precision_decimals": 3,  # 0.001 BTC
        },
        "5m_intraday": {
            "min_risk_pts": 350.0,
            "max_risk_pts": 1500.0,
            "t1_ceiling_pts": 2000.0,
            "t2_ceiling_pts": 3500.0,
            "atr_multiplier": 1.2,
            "min_rr": 1.35,
            "trigger_ttl_seconds": 600,
            "active_time_stop_seconds": 3600,
            "runner_ttl_seconds": 900,
            "precision_decimals": 3,
        },
    },
    "ETHUSDT": {
        "1m_scalp": {
            "min_risk_pts": 8.0,
            "max_risk_pts": 45.0,
            "t1_ceiling_pts": 60.0,
            "t2_ceiling_pts": 100.0,
            "atr_multiplier": 1.1,
            "min_rr": 1.25,
            "trigger_ttl_seconds": 180,
            "active_time_stop_seconds": 900,
            "runner_ttl_seconds": 300,
            "precision_decimals": 2,  # 0.01 ETH
        },
        "5m_intraday": {
            "min_risk_pts": 20.0,
            "max_risk_pts": 100.0,
            "t1_ceiling_pts": 150.0,
            "t2_ceiling_pts": 250.0,
            "atr_multiplier": 1.2,
            "min_rr": 1.35,
            "trigger_ttl_seconds": 600,
            "active_time_stop_seconds": 3600,
            "runner_ttl_seconds": 900,
            "precision_decimals": 2,
        },
    },
}


class CryptoCentralRiskEngine:
    """
    Evaluates crypto setups against institutional risk envelopes.
    Guarantees 'No structural stop clamping' — invalid wide stops are rejected outright.
    """

    def __init__(self, envelopes: Optional[dict] = None):
        self._envelopes = envelopes or CRYPTO_RISK_ENVELOPES

    def evaluate(
        self,
        setup: CryptoStrategySetup,
        available_equity_usd: float = 10_000.0,
        risk_per_trade_pct: float = 1.0,  # 1% equity ($100 risk)
    ) -> CryptoValidatedRiskDecision:
        sym = setup.symbol.upper()
        clean_sym = "BTCUSDT" if "BTC" in sym else ("ETHUSDT" if "ETH" in sym else "BTCUSDT")
        desk_key = "1m_scalp" if setup.is_scalp or setup.timeframe in ("1m", "3m") else "5m_intraday"

        symbol_rules = self._envelopes.get(clean_sym, {}).get(desk_key)
        if not symbol_rules:
            return self._reject("CONFIG_MISSING", f"No envelope configured for {clean_sym} ({desk_key})", setup)

        # 1. Calculate Raw Structural Risk
        is_short = setup.direction == "SHORT"
        if not is_short:
            raw_risk = float(setup.entry_trigger - setup.raw_structural_stop)
        else:
            raw_risk = float(setup.raw_structural_stop - setup.entry_trigger)

        if raw_risk <= 0:
            return self._reject(
                "INVALID_STOP_ORIENTATION",
                "Stop loss must be placed defensively relative to entry trigger",
                setup,
            )

        # 2. Safety Invariant: Reject oversized stops without clamping
        max_allowed_risk = float(symbol_rules["max_risk_pts"])
        min_allowed_risk = float(symbol_rules["min_risk_pts"])

        if raw_risk > max_allowed_risk:
            return self._reject(
                "STRUCTURAL_RISK_EXCEEDS_ENVELOPE",
                f"Structural risk (${raw_risk:.2f}) exceeds maximum envelope ceiling (${max_allowed_risk:.2f})",
                setup,
            )

        # Volatility buffer check (ensure stop isn't inside micro noise)
        atr_risk = float(setup.atr_val) * float(symbol_rules.get("atr_multiplier", 1.0))
        validated_risk = max(raw_risk, min_allowed_risk, atr_risk)

        if validated_risk > max_allowed_risk:
            return self._reject(
                "VOLATILITY_RISK_EXCEEDS_ENVELOPE",
                f"ATR-adjusted risk (${validated_risk:.2f}) exceeds maximum allowable ceiling (${max_allowed_risk:.2f})",
                setup,
            )

        # Calculate finalized Stop Loss
        validated_risk_dec = Decimal(str(round(validated_risk, 4)))
        if not is_short:
            final_sl = setup.entry_trigger - validated_risk_dec
        else:
            final_sl = setup.entry_trigger + validated_risk_dec

        # 3. Target Engine (Realistic Excursion + Ceiling)
        t1_ceiling = float(symbol_rules["t1_ceiling_pts"])
        t2_ceiling = float(symbol_rules["t2_ceiling_pts"])
        min_rr = float(symbol_rules["min_rr"])

        candidate_t1_pts = None
        for cand in setup.structural_target_candidates:
            diff = float(abs(cand - setup.entry_trigger))
            if (validated_risk * min_rr) <= diff <= t1_ceiling:
                candidate_t1_pts = diff
                break

        if not candidate_t1_pts:
            candidate_t1_pts = min(validated_risk * 1.5, t1_ceiling)

        candidate_t2_pts = min(max(candidate_t1_pts * 1.6, validated_risk * 2.2), t2_ceiling)

        rr_t1 = round(candidate_t1_pts / validated_risk, 2)
        if rr_t1 < min_rr:
            return self._reject(
                "INSUFFICIENT_RR",
                f"Reward provides only {rr_t1}R (Minimum required: {min_rr}R)",
                setup,
            )

        t1_pts_dec = Decimal(str(round(candidate_t1_pts, 4)))
        t2_pts_dec = Decimal(str(round(candidate_t2_pts, 4)))
        if not is_short:
            final_t1 = setup.entry_trigger + t1_pts_dec
            final_t2 = setup.entry_trigger + t2_pts_dec
        else:
            final_t1 = setup.entry_trigger - t1_pts_dec
            final_t2 = setup.entry_trigger - t2_pts_dec

        # 4. Fractional Coin Position Sizing
        risk_budget_usd = available_equity_usd * (risk_per_trade_pct / 100.0)
        decimals = int(symbol_rules.get("precision_decimals", 3))

        raw_qty = risk_budget_usd / validated_risk if validated_risk > 0 else 0.0
        # Quantize to coin decimals
        quantized_qty = round(math.floor(raw_qty * (10 ** decimals)) / (10 ** decimals), decimals)

        if quantized_qty <= 0:
            return self._reject(
                "INSUFFICIENT_CAPITAL_FOR_MIN_QUANTITY",
                f"Risk budget ${risk_budget_usd:.1f} cannot absorb minimum quantity at ${validated_risk:.2f} risk/unit",
                setup,
            )

        spot_f = float(setup.entry_trigger)
        notional_usd = round(quantized_qty * spot_f, 2)
        max_usd_loss = round(quantized_qty * validated_risk, 2)

        return CryptoValidatedRiskDecision(
            accepted=True,
            entry_price=setup.entry_trigger,
            stop_loss=final_sl,
            target_1=final_t1,
            target_2=final_t2,
            risk_points=round(validated_risk, 2),
            reward_t1_points=round(candidate_t1_pts, 2),
            reward_t2_points=round(candidate_t2_pts, 2),
            risk_reward_t1=rr_t1,
            risk_reward_t2=round(candidate_t2_pts / validated_risk, 2),
            trigger_ttl_seconds=int(symbol_rules["trigger_ttl_seconds"]),
            active_time_stop_seconds=int(symbol_rules["active_time_stop_seconds"]),
            runner_ttl_seconds=int(symbol_rules.get("runner_ttl_seconds", 300)),
            quantity=quantized_qty,
            notional_usd=notional_usd,
            max_usd_loss=max_usd_loss,
            precision_decimals=decimals,
        )

    def _reject(self, reason_code: str, message: str, setup: CryptoStrategySetup) -> CryptoValidatedRiskDecision:
        logger.info(
            "crypto_risk_decision_rejected",
            strategy=setup.strategy_name,
            symbol=setup.symbol,
            reason=reason_code,
            message=message,
        )
        return CryptoValidatedRiskDecision(
            accepted=False,
            rejection_reason=f"{reason_code}: {message}",
            entry_price=setup.entry_trigger,
            stop_loss=setup.raw_structural_stop,
            target_1=Decimal("0"),
            target_2=Decimal("0"),
            risk_points=0.0,
            reward_t1_points=0.0,
            reward_t2_points=0.0,
            risk_reward_t1=0.0,
            risk_reward_t2=0.0,
            trigger_ttl_seconds=0,
            active_time_stop_seconds=0,
            quantity=0.0,
            notional_usd=0.0,
            max_usd_loss=0.0,
        )


crypto_risk_engine = CryptoCentralRiskEngine()
