"""
Standard human-readable reason codes for VORTEX-SNAP Strategy Engine (§42).
"""
from __future__ import annotations

from enum import Enum


class ReasonCode(str, Enum):
    # Activation and confirmation codes
    COMPRESSION_EXTREME = "COMPRESSION_EXTREME"
    COMPRESSION_ARMED = "COMPRESSION_ARMED"
    PRESSURE_POSITIVE = "PRESSURE_POSITIVE"
    PRESSURE_NEGATIVE = "PRESSURE_NEGATIVE"
    TRANSLATION_HIGH = "TRANSLATION_HIGH"
    TRANSLATION_RECOVERY = "TRANSLATION_RECOVERY"
    VACUUM_CONFIRMED = "VACUUM_CONFIRMED"
    SNAP_ENERGY_HIGH = "SNAP_ENERGY_HIGH"
    SNAP_ENERGY_EXPLOSIVE = "SNAP_ENERGY_EXPLOSIVE"
    RESISTANCE_BROKEN = "RESISTANCE_BROKEN"
    SUPPORT_BROKEN = "SUPPORT_BROKEN"
    LEVEL_RETEST_HELD = "LEVEL_RETEST_HELD"
    LEVEL_ABSORPTION_CONFIRMED = "LEVEL_ABSORPTION_CONFIRMED"
    TRAP_RECLAIM_CONFIRMED = "TRAP_RECLAIM_CONFIRMED"
    REGIME_TREND_ALIGNED = "REGIME_TREND_ALIGNED"
    REGIME_RANGE_ALIGNED = "REGIME_RANGE_ALIGNED"
    FOLLOW_THROUGH_CONFIRMED = "FOLLOW_THROUGH_CONFIRMED"
    ML_VALIDATION_PASS = "ML_VALIDATION_PASS"

    # Rejection and No-Trade codes (§18, §42)
    COMPRESSION_INSUFFICIENT = "COMPRESSION_INSUFFICIENT"
    TRANSLATION_WEAK = "TRANSLATION_WEAK"
    PRESSURE_CONFLICT = "PRESSURE_CONFLICT"
    BREAKOUT_FAILED = "BREAKOUT_FAILED"
    REGIME_CHAOTIC = "REGIME_CHAOTIC"
    REGIME_CONFLICT = "REGIME_CONFLICT"
    NO_TRADE_WINDOW = "NO_TRADE_WINDOW"
    FORCED_SQUARE_OFF = "FORCED_SQUARE_OFF"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    DAILY_LOSS_LIMIT_REACHED = "DAILY_LOSS_LIMIT_REACHED"
    CONSECUTIVE_LOSS_LIMIT = "CONSECUTIVE_LOSS_LIMIT"
    DATA_QUALITY_FAIL = "DATA_QUALITY_FAIL"
    DATA_STALE = "DATA_STALE"
    SLIPPAGE_TOO_HIGH = "SLIPPAGE_TOO_HIGH"
    CORRELATED_EXPOSURE_ACTIVE = "CORRELATED_EXPOSURE_ACTIVE"
    ML_PROBABILITY_LOW = "ML_PROBABILITY_LOW"
    CONFIRMATION_TIMEOUT = "CONFIRMATION_TIMEOUT"
    INVALIDATED_BY_STRUCTURE = "INVALIDATED_BY_STRUCTURE"
    PRESSURE_COLLAPSED = "PRESSURE_COLLAPSED"
