'use client';

import { useMemo, useState } from 'react';
import type { Trade } from '@/lib/api/indicatorResearch';
import { fmt, fmtInt, fmtMoney, fmtPct, fmtStamp, toneClass } from '@/lib/indicatorResearch';

const PAGE = 100;

type Props = {
  trades: Trade[];
  totalCount: number;
};

export function TradeTable({ trades, totalCount }: Props) {
  const [side, setSide] = useState<'all' | 'LONG' | 'SHORT'>('all');
  const [reason, setReason] = useState<string>('all');
  const [limit, setLimit] = useState(PAGE);
  const [sortKey, setSortKey] = useState<'entry' | 'net' | 'return' | 'mae' | 'mfe' | 'bars'>('entry');
  const [desc, setDesc] = useState(false);

  const reasons = useMemo(() => {
    const set = new Set<string>();
    for (const t of trades) if (t.exit_reason) set.add(t.exit_reason);
    return [...set].sort();
  }, [trades]);

  const rows = useMemo(() => {
    const filtered = trades.filter((t) => {
      if (side !== 'all' && t.side !== side) return false;
      if (reason !== 'all' && t.exit_reason !== reason) return false;
      return true;
    });
    const pick = (t: Trade): number => {
      switch (sortKey) {
        case 'net':
          return t.net_pnl;
        case 'return':
          return t.return_pct;
        case 'mae':
          return t.mae_pct;
        case 'mfe':
          return t.mfe_pct;
        case 'bars':
          return t.bars_held;
        default:
          return t.entry_index;
      }
    };
    const sorted = [...filtered].sort((a, b) => (desc ? pick(b) - pick(a) : pick(a) - pick(b)));
    return sorted;
  }, [trades, side, reason, sortKey, desc]);

  const header = (key: typeof sortKey, label: string) => (
    <th
      className="cursor-pointer select-none whitespace-nowrap text-right"
      title={`Sort by ${label}`}
      onClick={() => {
        if (sortKey === key) setDesc((v) => !v);
        else {
          setSortKey(key);
          setDesc(true);
        }
      }}
    >
      {label}
      {sortKey === key ? <span className="faint"> {desc ? '↓' : '↑'}</span> : null}
    </th>
  );

  if (trades.length === 0) {
    return (
      <div className="flex h-24 items-center justify-center rounded-md border border-border-subtle bg-surface-subtle">
        <p className="sg-note">No trades were generated by these rules on this window.</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-2">
      <div className="flex flex-wrap items-center gap-2">
        <div className="seg">
          {(['all', 'LONG', 'SHORT'] as const).map((s) => (
            <button key={s} type="button" className={`seg-btn ${side === s ? 'is-active' : ''}`} onClick={() => setSide(s)}>
              {s === 'all' ? 'All sides' : s === 'LONG' ? 'Long' : 'Short'}
            </button>
          ))}
        </div>
        <label className="field w-auto">
          <span className="field-l">Exit reason</span>
          <select className="input py-0.5 text-[11px]" value={reason} onChange={(e) => setReason(e.target.value)}>
            <option value="all">all</option>
            {reasons.map((r) => (
              <option key={r} value={r}>
                {r}
              </option>
            ))}
          </select>
        </label>
        <span className="card-meta num ml-auto">
          showing {fmtInt(Math.min(limit, rows.length))} of {fmtInt(rows.length)}
          {rows.length !== totalCount ? ` (${fmtInt(totalCount)} total)` : ''}
        </span>
      </div>

      <div className="tbl-scroll max-h-[26rem] overflow-auto">
        <table className="tbl tbl--zebra tbl-dense tbl--sticky w-full">
          <thead>
            <tr>
              <th className="w-8">#</th>
              <th>Side</th>
              {header('entry', 'Signal → Entry')}
              <th className="text-right">Entry</th>
              <th className="text-right">Exit</th>
              <th>Reason</th>
              {header('bars', 'Bars')}
              <th className="text-right">Qty</th>
              <th className="text-right">Costs</th>
              {header('return', 'Return %')}
              {header('mae', 'MAE %')}
              {header('mfe', 'MFE %')}
              {header('net', 'Net P&L')}
              <th>Regime</th>
              <th>TOD</th>
            </tr>
          </thead>
          <tbody>
            {rows.slice(0, limit).map((t) => (
              <tr key={t.trade_id}>
                <td className="num text-ink-3">{t.trade_id}</td>
                <td>
                  <span className={`badge badge-sm ${t.side === 'LONG' ? 'b-bull' : 'b-bear'}`}>{t.side}</span>
                </td>
                <td className="whitespace-nowrap text-ink-2">
                  <span title={`signal ${t.signal_time ?? '—'}`}>{fmtStamp(t.signal_time, false)}</span>
                  <span className="faint"> → </span>
                  <span title={`entry ${t.entry_time ?? '—'}`}>{fmtStamp(t.entry_time, false)}</span>
                </td>
                <td className="col-num">
                  {fmt(t.entry_price, 2)}
                  {Math.abs(t.entry_reference_price - t.entry_price) > 1e-9 ? (
                    <span className="faint ml-1" title={`signal-bar close ${fmt(t.entry_reference_price, 2)}`}>
                      *
                    </span>
                  ) : null}
                </td>
                <td className="col-num">{t.exit_price === null ? '—' : fmt(t.exit_price, 2)}</td>
                <td className="whitespace-nowrap text-[11px] text-ink-2">{t.exit_reason ?? '—'}</td>
                <td className="col-num">{t.bars_held}</td>
                <td className="col-num">{fmt(t.quantity, 2)}</td>
                <td className="col-num text-warn-strong">{fmt(t.costs, 0)}</td>
                <td className={`col-num ${toneClass(t.return_pct)}`}>{fmtPct(t.return_pct)}</td>
                <td className="col-num text-ink-2">{fmt(t.mae_pct, 2)}</td>
                <td className="col-num text-ink-2">{fmt(t.mfe_pct, 2)}</td>
                <td className={`col-num ${toneClass(t.net_pnl)}`}>{fmtMoney(t.net_pnl)}</td>
                <td className="text-[11px] text-ink-3">{t.regime ?? '—'}</td>
                <td className="text-[11px] text-ink-3">{t.time_bucket ?? '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {rows.length > limit ? (
        <button type="button" className="btn btn-ic w-fit" onClick={() => setLimit((v) => v + PAGE * 2)}>
          Show more ({fmtInt(rows.length - limit)} remaining)
        </button>
      ) : null}

      <p className="faint text-[10px]">
        * entry price differs from the signal-bar close — the fill happened on the next bar, as configured.
      </p>
    </div>
  );
}
