"""
Centralized Risk, Target, & Sizing Authority — §4, §5, §6, §10, §15, §18
Enforces:
  1. No structural stop clamping (Reject invalid structure instead of forcing arbitrary tight stop).
  2. Realistic target generation based on market structure and envelope ceilings.
  3. Strict integer-lot position sizing.
  4. Independent Two-Clock lifecycles (Trigger TTL vs Active Holding Time Stop).
"""
from __future__ import annotations

import json
import math
import os
from decimal import Decimal
from pathlib import Path
from typing import Literal, Optional
from pydantic import BaseModel, Field
import structlog

logger = structlog.get_logger()

Direction = Literal["LONG_CALL", "LONG_PUT"]
Timeframe = Literal["1M", "3M", "5M", "15M", "1D"]


class StrategySetup(BaseModel):
    """Raw proposal generated by an individual strategy algorithm."""
    strategy_name: str
    underlying: Literal["NIFTY", "BANKNIFTY", "SENSEX"]
    direction: Direction
    timeframe: Timeframe = "5M"
    is_scalp: bool = False
    spot_price: Decimal
    entry_trigger: Decimal
    raw_structural_stop: Decimal
    structural_target_candidates: list[Decimal] = Field(default_factory=list)
    atr_5m: Decimal = Decimal("22.0")
    confidence: float = 75.0


class ValidatedRiskDecision(BaseModel):
    accepted: bool
    rejection_reason: Optional[str] = None
    config_version: int = 1

    # Final validated prices
    entry_price: Decimal
    stop_loss: Decimal
    target_1: Decimal
    target_2: Decimal

    # Risk / Reward metrics
    risk_points: float
    reward_t1_points: float
    reward_t2_points: float
    risk_reward_t1: float
    risk_reward_t2: float

    # Independent Lifecycles
    trigger_ttl_seconds: int
    active_time_stop_seconds: int

    # Position Sizing
    lots: int
    quantity: int
    max_rupee_loss: float
    lot_size: int


class CentralRiskEngine:
    def __init__(self, config_file: Optional[str] = None):
        self.config_file = config_file
        self._config = self._load_config()

    def _load_config(self) -> dict:
        candidates = []
        if self.config_file:
            candidates.append(Path(self.config_file))
        
        # Look in common repo locations
        candidates.extend([
            Path(__file__).resolve().parents[2] / "config" / "risk_envelopes.json",
            Path("backend/config/risk_envelopes.json"),
            Path("config/risk_envelopes.json"),
        ])

        for p in candidates:
            if p.exists():
                try:
                    with open(p, "r", encoding="utf-8") as f:
                        data = json.load(f)
                        logger.info("risk_engine_config_loaded", path=str(p), version=data.get("version", 1))
                        return data
                except Exception as e:
                    logger.warning("risk_engine_config_read_error", path=str(p), error=str(e))

        # Fallback defaults
        return {
            "version": 1,
            "envelopes": {
                "NIFTY": {
                    "1m_scalp": {"min_risk_pts": 8.0, "max_risk_pts": 18.0, "t1_ceiling_pts": 30.0, "t2_ceiling_pts": 45.0, "atr_multiplier": 1.1, "min_rr": 1.25, "trigger_ttl_seconds": 180, "active_time_stop_seconds": 900},
                    "5m_intraday": {"min_risk_pts": 18.0, "max_risk_pts": 35.0, "t1_ceiling_pts": 55.0, "t2_ceiling_pts": 80.0, "atr_multiplier": 1.2, "min_rr": 1.35, "trigger_ttl_seconds": 600, "active_time_stop_seconds": 4500},
                },
                "BANKNIFTY": {
                    "1m_scalp": {"min_risk_pts": 25.0, "max_risk_pts": 50.0, "t1_ceiling_pts": 75.0, "t2_ceiling_pts": 120.0, "atr_multiplier": 1.1, "min_rr": 1.25, "trigger_ttl_seconds": 180, "active_time_stop_seconds": 900},
                    "5m_intraday": {"min_risk_pts": 50.0, "max_risk_pts": 95.0, "t1_ceiling_pts": 140.0, "t2_ceiling_pts": 220.0, "atr_multiplier": 1.2, "min_rr": 1.35, "trigger_ttl_seconds": 600, "active_time_stop_seconds": 4500},
                },
                "SENSEX": {
                    "5m_intraday": {"min_risk_pts": 70.0, "max_risk_pts": 130.0, "t1_ceiling_pts": 180.0, "t2_ceiling_pts": 300.0, "atr_multiplier": 1.2, "min_rr": 1.35, "trigger_ttl_seconds": 600, "active_time_stop_seconds": 4500},
                }
            },
            "lot_sizes": {"NIFTY": 75, "BANKNIFTY": 30, "SENSEX": 10, "FINNIFTY": 65, "MIDCPNIFTY": 120},
            "options_scaling": {"default_atm_delta": 0.50, "expiry_day_time_stop_factor": 0.50}
        }

    def evaluate(
        self,
        setup: StrategySetup,
        available_capital: float = 100000.0,
        risk_per_trade_pct: float = 1.0,
        is_expiry_day: bool = False,
    ) -> ValidatedRiskDecision:
        desk_key = "1m_scalp" if setup.is_scalp or setup.timeframe in ("1M", "3M") else "5m_intraday"
        underlying_rules = self._config.get("envelopes", {}).get(setup.underlying, {}).get(desk_key)

        if not underlying_rules:
            return self._reject("CONFIG_MISSING", f"No envelope configured for {setup.underlying} ({desk_key})", setup)

        # ── 1. Calculate Raw Structural Risk ──
        if setup.direction == "LONG_CALL":
            raw_risk = float(setup.entry_trigger - setup.raw_structural_stop)
        else:
            raw_risk = float(setup.raw_structural_stop - setup.entry_trigger)

        if raw_risk <= 0:
            return self._reject("INVALID_STOP_ORIENTATION", "Stop loss must be placed defensively relative to entry trigger", setup)

        # ── 2. The Core Safety Invariant: Reject oversized stops ──
        max_allowed_risk = float(underlying_rules["max_risk_pts"])
        min_allowed_risk = float(underlying_rules["min_risk_pts"])

        if raw_risk > max_allowed_risk:
            # CRITICAL SAFETY INVARIANT: DO NOT clamp an invalid wide stop inward. REJECT.
            return self._reject(
                "STRUCTURAL_RISK_EXCEEDS_ENVELOPE",
                f"Required structural risk ({raw_risk:.1f} pts) exceeds maximum envelope ceiling ({max_allowed_risk:.1f} pts)",
                setup,
            )

        # Volatility-based buffer check (stop should not be tighter than micro ATR)
        atr_risk = float(setup.atr_5m) * float(underlying_rules.get("atr_multiplier", 1.0))
        validated_risk = max(raw_risk, min_allowed_risk, atr_risk)

        if validated_risk > max_allowed_risk:
            return self._reject(
                "VOLATILITY_RISK_EXCEEDS_ENVELOPE",
                f"ATR-adjusted risk ({validated_risk:.1f} pts) exceeds max allowable envelope ceiling ({max_allowed_risk:.1f} pts)",
                setup,
            )

        # Calculate finalized Stop Loss price
        validated_risk_dec = Decimal(str(round(validated_risk, 2)))
        if setup.direction == "LONG_CALL":
            final_sl = setup.entry_trigger - validated_risk_dec
        else:
            final_sl = setup.entry_trigger + validated_risk_dec

        # ── 3. Target Engine (Realistic Excursion + Ceiling) ──
        t1_ceiling = float(underlying_rules["t1_ceiling_pts"])
        t2_ceiling = float(underlying_rules["t2_ceiling_pts"])
        min_rr = float(underlying_rules["min_rr"])

        # Check candidate targets from strategy proposals that are reachable within ceiling
        candidate_t1_pts = None
        for cand in setup.structural_target_candidates:
            diff = float(abs(cand - setup.entry_trigger))
            if diff >= (validated_risk * min_rr) and diff <= t1_ceiling:
                candidate_t1_pts = diff
                break

        # Fallback to standard 1.5R bounded by ceiling if no candidate fit
        if not candidate_t1_pts:
            candidate_t1_pts = min(validated_risk * 1.5, t1_ceiling)

        candidate_t2_pts = min(max(candidate_t1_pts * 1.6, validated_risk * 2.0), t2_ceiling)

        rr_t1 = round(candidate_t1_pts / validated_risk, 2)
        if rr_t1 < min_rr:
            return self._reject(
                "INSUFFICIENT_RR",
                f"Realistic reward provides only {rr_t1}R (Minimum required: {min_rr}R)",
                setup,
            )

        # Finalized Target Prices
        t1_pts_dec = Decimal(str(round(candidate_t1_pts, 2)))
        t2_pts_dec = Decimal(str(round(candidate_t2_pts, 2)))
        if setup.direction == "LONG_CALL":
            final_t1 = setup.entry_trigger + t1_pts_dec
            final_t2 = setup.entry_trigger + t2_pts_dec
        else:
            final_t1 = setup.entry_trigger - t1_pts_dec
            final_t2 = setup.entry_trigger - t2_pts_dec

        # ── 4. Position Sizing (Integer Lots Only) ──
        lot_size = int(self._config.get("lot_sizes", {}).get(setup.underlying, 75))
        allowed_rupee_risk = available_capital * (risk_per_trade_pct / 100.0)

        # In index options, stop loss in spot translates via ATM delta (~0.50)
        delta = float(self._config.get("options_scaling", {}).get("default_atm_delta", 0.50))
        option_risk_per_unit = validated_risk * delta
        rupee_risk_per_lot = option_risk_per_unit * lot_size

        lots = math.floor(allowed_rupee_risk / rupee_risk_per_lot) if rupee_risk_per_lot > 0 else 0
        if lots < 1:
            return self._reject(
                "INSUFFICIENT_CAPITAL_FOR_1_LOT",
                f"Budget ₹{allowed_rupee_risk:.0f} cannot absorb ₹{rupee_risk_per_lot:.0f} risk per lot for {lot_size} qty",
                setup,
            )

        lots = min(lots, 10)  # Max 10 lots safety cap
        total_qty = lots * lot_size
        max_rupee_loss = round(total_qty * option_risk_per_unit, 2)

        # ── 5. Independent Lifecycle Clocks ──
        time_stop = int(underlying_rules["active_time_stop_seconds"])
        if is_expiry_day:
            time_stop = int(time_stop * float(self._config.get("options_scaling", {}).get("expiry_day_time_stop_factor", 0.5)))

        return ValidatedRiskDecision(
            accepted=True,
            config_version=int(self._config.get("version", 1)),
            entry_price=setup.entry_trigger,
            stop_loss=final_sl,
            target_1=final_t1,
            target_2=final_t2,
            risk_points=round(validated_risk, 2),
            reward_t1_points=round(candidate_t1_pts, 2),
            reward_t2_points=round(candidate_t2_pts, 2),
            risk_reward_t1=rr_t1,
            risk_reward_t2=round(candidate_t2_pts / validated_risk, 2),
            trigger_ttl_seconds=int(underlying_rules["trigger_ttl_seconds"]),
            active_time_stop_seconds=time_stop,
            lots=lots,
            quantity=total_qty,
            max_rupee_loss=max_rupee_loss,
            lot_size=lot_size,
        )

    def _reject(self, reason_code: str, message: str, setup: StrategySetup) -> ValidatedRiskDecision:
        lot_size = int(self._config.get("lot_sizes", {}).get(setup.underlying, 75))
        logger.info(
            "risk_engine_trade_rejected",
            strategy=setup.strategy_name,
            underlying=setup.underlying,
            reason=reason_code,
            message=message,
        )
        return ValidatedRiskDecision(
            accepted=False,
            rejection_reason=f"{reason_code}: {message}",
            entry_price=setup.entry_trigger,
            stop_loss=setup.raw_structural_stop,
            target_1=Decimal("0"),
            target_2=Decimal("0"),
            risk_points=0.0,
            reward_t1_points=0.0,
            reward_t2_points=0.0,
            risk_reward_t1=0.0,
            risk_reward_t2=0.0,
            trigger_ttl_seconds=0,
            active_time_stop_seconds=0,
            lots=0,
            quantity=0,
            max_rupee_loss=0.0,
            lot_size=lot_size,
        )


central_risk_engine = CentralRiskEngine()


def resolve_realistic_atr(underlying: str, spot: Decimal, indicators: Optional[dict] = None) -> Decimal:
    """Derive clean, realistic 5M ATR bounded strictly to intraday index norms."""
    ind = indicators or {}
    raw_atr = ind.get("atr") or ind.get("volatility", {}).get("atr")
    if raw_atr:
        try:
            val = Decimal(str(raw_atr))
            if val > 0:
                if underlying == "NIFTY":
                    return min(Decimal("32.0"), max(Decimal("14.0"), val))
                elif underlying == "BANKNIFTY":
                    return min(Decimal("90.0"), max(Decimal("35.0"), val))
                elif underlying == "SENSEX":
                    return min(Decimal("130.0"), max(Decimal("50.0"), val))
                return val
        except Exception:
            pass

    # Baseline norms (approx 1.0x 5M candle range)
    if underlying == "NIFTY":
        return Decimal("20.0")
    elif underlying == "BANKNIFTY":
        return Decimal("55.0")
    elif underlying == "SENSEX":
        return Decimal("85.0")
    return spot * Decimal("0.001")

